USE [COMP_FIRM]
GO

/****** Object:  Table [dbo].[ComponentsImage]    Script Date: 07.06.2022 12:08:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ComponentsImage](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idC] [int] NOT NULL,
	[Image] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ComponentsImage]  WITH CHECK ADD FOREIGN KEY([idC])
REFERENCES [dbo].[Components] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

