//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadImage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentsImage
    {
        public int id { get; set; }
        public int idC { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Components Components { get; set; }
    }
}
